### ISSUE TITLE
Package available in Puppet Forge is empty

### ISSUE THREAD

**Issue by joaquimpedrooliveira** [dsestero/java#2]
When downloading the module from https://forge.puppet.com/v3/files/dsestero-java-1.1.1.tar.gz, the file does not contain the module directories:

`~/Desktop$ tree dsestero-java-1.1.1`
`dsestero-java-1.1.1`
`├── checksums.json`
`└── metadata.json`
` `
`0 directories, 2 files`

**Comment by dsestero** [comment]
Joaquim Pedro,

thanks for notifying it. I suppose something went wrong when I made last release. Now I released version 1.1.2 that seems to be ok.

`tar tfz pkg/dsestero-java-1.1.2.tar.gz `
`dsestero-java-1.1.2/`
`dsestero-java-1.1.2/LICENSE`
`dsestero-java-1.1.2/Rakefile`
`dsestero-java-1.1.2/manifests/`
`dsestero-java-1.1.2/manifests/install_config.pp`
`dsestero-java-1.1.2/manifests/java_7.pp`
`dsestero-java-1.1.2/manifests/java_6.pp`
`dsestero-java-1.1.2/manifests/java_8.pp`
`dsestero-java-1.1.2/manifests/init.pp`
`dsestero-java-1.1.2/tests/`
`dsestero-java-1.1.2/tests/init.pp`
`dsestero-java-1.1.2/spec/`
`dsestero-java-1.1.2/spec/fixtures/`
`dsestero-java-1.1.2/spec/fixtures/manifests/`
`dsestero-java-1.1.2/spec/fixtures/manifests/site.pp`
`dsestero-java-1.1.2/spec/fixtures/modules/`
`dsestero-java-1.1.2/spec/fixtures/modules/java/`
`dsestero-java-1.1.2/spec/fixtures/modules/java/manifests/`
`dsestero-java-1.1.2/spec/spec_helper.rb`
`dsestero-java-1.1.2/spec/spec.opts`
`dsestero-java-1.1.2/spec/hosts/`
`dsestero-java-1.1.2/spec/functions/`
`dsestero-java-1.1.2/spec/defines/`
`dsestero-java-1.1.2/spec/defines/config_spec.rb`
`dsestero-java-1.1.2/spec/defines/install_spec.rb`
`dsestero-java-1.1.2/spec/defines/java_spec.rb`
`dsestero-java-1.1.2/spec/classes/`
`dsestero-java-1.1.2/metadata.json`
`dsestero-java-1.1.2/checksums.json`
`dsestero-java-1.1.2/README.markdown`
`dsestero-java-1.1.2/CHANGELOG.md`

Ciao
Dario
